In [1]:
import tensorflow as tf

2023-01-24 14:13:49.174264: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
tf.executing_eagerly()

True

In [3]:
x = [[10.]]
res = tf.matmul(x, x)
res

2023-01-24 14:15:09.519371: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[100.]], dtype=float32)>

In [4]:
a = tf.constant([[10, 20], 
                 [30, 40]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [5]:
b = tf.add(a, 2)
print(b)

tf.Tensor(
[[12 22]
 [32 42]], shape=(2, 2), dtype=int32)


In [6]:
print(a*b)

tf.Tensor(
[[ 120  440]
 [ 960 1680]], shape=(2, 2), dtype=int32)


In [7]:
m = tf.Variable([4.0, 5.0, 6.0], tf.float32, name='m')
c = tf.Variable([1.0, 1.0, 1.0], tf.float32, name='c')
# initalized automatically due to eager execution, no need for separate operation

<tf.Variable 'c:0' shape=(3,) dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [8]:
m

<tf.Variable 'm:0' shape=(3,) dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>

In [9]:
c

<tf.Variable 'c:0' shape=(3,) dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [10]:
#evaluates right away, no need for placeholder
x = tf.Variable([100.0, 100.0, 100.0], tf.float32, name='x')
x

<tf.Variable 'x:0' shape=(3,) dtype=float32, numpy=array([100., 100., 100.], dtype=float32)>

In [11]:
y = m*x + c
y

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([401., 501., 601.], dtype=float32)>

In [12]:
# eager execution allows conditional statements, for-loops, etc.